#Requires AutoHotkey v2.0

; Milder wording after the trigger + an ending character (space, punctuation, Enter).
; Longer phrases first where a shorter word is a prefix (e.g. fucking before fuck).
; Formerly ahk\autorun\softer.ahk — now one process with autocorrect.ahk.

; --- phrases ---
:B0:what the fuck::f("what the heck")
:B0:what the hell::f("what the heck")
:B0:holy shit::f("holy cow")
:B0:pissed off::f("ticked off")
:B0:piss off::f("go away")
; no bare "piss" — it would break "piss off"
:B0:god damn::f("dang")
:B0:goddamn::f("dang")
:B0:damn it::f("dang it")
:B0:dammit::f("dang it")
:B0:piece of shit::f("real mess")
:B0:son of a bitch::f("son of a gun")
:B0:bullshit::f("baloney")
:B0:dumb ass::f("silly goose")
:B0:dumbass::f("silly goose")
:B0:jackass::f("jerk")
:B0:smartass::f("smart aleck")
:B0:badass::f("tough cookie")
:B0:hard ass::f("hard case")
:B0:fat ass::f("large person")
:B0:kiss my ass::f("take a hike")
:B0:pain in the ass::f("pain in the neck")
:B0:pain in the butt::f("pain in the neck")
:B0:up yours::f("oh, buzz off")
:B0:screw you::f("forget you")
:B0:fuck off::f("go away")
:B0:fuck you::f("leave me alone")
:B0:clusterfuck::f("total mess")
:B0:rat bastard::f("real jerk")

; --- words (strong → softer) ---
:B0:motherfucker::f("jerk")
:B0:motherfucking::f("freaking")
:B0:bullshitter::f("fibber")
:B0:shithead::f("jerk")
:B0:shitty::f("lousy")
:B0:shitting::f("freaking out over")
:B0:shit::f("shoot")
:B0:fucking::f("freaking")
:B0:fucked up::f("messed up")
:B0:fucked::f("messed")
:B0:fucker::f("jerk")
:B0:fuck::f("fudge")
:B0:bitchy::f("snippy")
:B0:bitch::f("jerk")
:B0:bastard::f("jerk")
:B0:asshole::f("jerk")
:B0:arsehole::f("jerk")
:B0:dickhead::f("jerk")
:B0:dickish::f("jerky")
:B0:dick::f("jerk")
:B0:cocksucker::f("jerk")
:B0:prick::f("jerk")
:B0:twat::f("jerk")
:B0:wanker::f("jerk")
:B0:douchebag::f("jerk")
:B0:douche::f("jerk")
:B0:crap::f("crud")
:B0:damn::f("darn")
:B0:hell::f("heck")
:B0:bastards::f("jerks")
:B0:bitches::f("jerks")
:B0:asses::f("butts")

; --- abbreviations / netspeak ---
:B0:wtf::f("what the heck")
:B0:wth::f("what the heck")
:B0:omfg::f("oh my goodness")
:B0:stfu::f("zip it")
:B0:gtfo::f("go away")
:B0:fml::f("rough day")
:B0:ffs::f("for crying out loud")
