#Requires AutoHotkey v2.0

; Expands casual / netspeak and a few letter-style abbreviations after you type
; the shorthand and an ending character (space, period, comma, Enter, etc.).
; --- casual / internet ---
:B0:idk::f("I don't know")
:B0:idc::f("I don't care")
:B0:iirc::f("if I remember correctly")
:B0:imo::f("in my opinion")
:B0:imho::f("in my humble opinion")
:B0:fwiw::f("for what it's worth")
:B0:tbh::f("to be honest")
:B0:ngl::f("not gonna lie")
:B0:tbf::f("to be fair")
:B0:fyi::f("for your information")
:B0:aka::f("also known as")
:B0:wdym::f("what do you mean")
:B0:ikr::f("I know, right?")
:B0:rn::f("right now")
:B0:bc::f("because")
:B0:tho::f("though")
:B0:pls::f("please")
:B0:plz::f("please")
:B0:thx::f("thanks")
:B0:ty::f("thank you")
:B0:np::f("no problem")
:B0:yw::f("you're welcome")
:B0:sry::f("sorry")
:B0:obvi::f("obviously")
:B0:def::f("definitely")
:B0:prob::f("probably")
:B0:prolly::f("probably")
:B0:gonna::f("going to")
:B0:wanna::f("want to")
:B0:kinda::f("kind of")
:B0:sorta::f("sort of")
:B0:dunno::f("don't know")
:B0:cuz::f("because")
:B0:til::f("today I learned")
:B0:afaik::f("as far as I know")
:B0:asap::f("as soon as possible")
:B0:eta::f("estimated time of arrival")
:B0:ttyl::f("talk to you later")
:B0:brb::f("be right back")
:B0:afk::f("away from keyboard")
:B0:omw::f("on my way")
:B0:lmk::f("let me know")
:B0:nvm::f("never mind")
:B0:jk::f("just kidding")
:B0:irl::f("in real life")
:B0:ftw::f("for the win")
:B0:ftr::f("for the record")
:B0:btw::f("by the way")
:B0:wrt::f("with respect to")
:B0:tldr::f("tl`;dr")

; --- letter / telegram-ish (longer triggers to avoid collisions) ---
:B0:postscript::f("P.S.")
:B0:regards::f("Best regards,")
:B0:kindregards::f("Kind regards,")
:B0:yrssinc::f("Yours sincerely,")
:B0:yrstruly::f("Yours truly,")
:B0:recd::f("received")
:B0:ansg::f("answer by return")
:B0:refg::f("in reference to your")
:B0:shdl::f("should")
:B0:wld::f("would")
:B0:cld::f("could")
:B0:abt::f("about")
:B0:acct::f("account")
:B0:addr::f("address")
:B0:bcoz::f("because")
:B0:dept::f("department")
:B0:govt::f("government")
:B0:misc::f("miscellaneous")
:B0:mth::f("month")
:B0:pple::f("people")
:B0:qt::f("quantity")
:B0:wk::f("week")
:B0:ytd::f("year to date")

; "without" shorthand (avoided w/o — can mangle paths)
:B0:wout::f("without")
