#Requires AutoHotkey v2.0
#SingleInstance Force

; Derived from MS Word AutoCorrect list 3-5-2026.
; Included by ..\autocorrect.ahk (master sets #SingleInstance when used there).
:B0:(c)::f("©")
:B0:(e)::f("€")
:B0:(r)::f("®")
:B0:(tm)::f("™")
:B0:...::f("…")
:B0:abbout::f("about")
:B0:abotu::f("about")
:B0:abouta::f("about a")
:B0:aboutit::f("about it")
:B0:aboutthe::f("about the")
:B0:abscence::f("absence")
:B0:accesories::f("accessories")
:B0:accidant::f("accident")
:B0:accomodate::f("accommodate")
:B0:accordingto::f("according to")
:B0:accross::f("across")
:B0:acheive::f("achieve")
:B0:acheived::f("achieved")
:B0:acheiving::f("achieving")
:B0:acn::f("can")
:B0:acommodate::f("accommodate")
:B0:acomodate::f("accommodate")
:B0:actualyl::f("actually")
:B0:additinal::f("additional")
:B0:addtional::f("additional")
:B0:adequit::f("adequate")
:B0:adequite::f("adequate")
:B0:adn::f("and")
:B0:advanage::f("advantage")
:B0:affraid::f("afraid")
:B0:afterthe::f("after the")
:B0:againstt he::f("against the")
:B0:aganist::f("against")
:B0:aggresive::f("aggressive")
:B0:agian::f("again")
:B0:agreemeent::f("agreement")
:B0:agreemeents::f("agreements")
:B0:agreemnet::f("agreement")
:B0:agreemnets::f("agreements")
:B0:agressive::f("aggressive")
:B0:ahppen::f("happen")
:B0:ahve::f("have")
:B0:allwasy::f("always")
:B0:allwyas::f("always")
:B0:almots::f("almost")
:B0:almsot::f("almost")
:B0:alomst::f("almost")
:B0:alot::f("a lot")
:B0:alraedy::f("already")
:B0:alreayd::f("already")
:B0:alreday::f("already")
:B0:alwasy::f("always")
:B0:alwats::f("always")
:B0:alway::f("always")
:B0:alwyas::f("always")
:B0:amde::f("made")
:B0:Ameria::f("America")
:B0:amke::f("make")
:B0:amkes::f("makes")
:B0:anbd::f("and")
:B0:andone::f("and one")
:B0:andt he::f("and the")
:B0:andteh::f("and the")
:B0:andthe::f("and the")
:B0:anothe::f("another")
:B0:anual::f("annual")
:B0:apparant::f("apparent")
:B0:apparrent::f("apparent")
:B0:appearence::f("appearance")
:B0:appeares::f("appears")
:B0:applicaiton::f("application")
:B0:applicaitons::f("applications")
:B0:applyed::f("applied")
:B0:appointiment::f("appointment")
:B0:approrpiate::f("appropriate")
:B0:approrpriate::f("appropriate")
:B0:aquisition::f("acquisition")
:B0:aquisitions::f("acquisitions")
:B0:aren;t::f("aren’t")
:B0:arguement::f("argument")
:B0:arguements::f("arguments")
:B0:arn't::f("aren’t")
:B0:arond::f("around")
:B0:artical::f("article")
:B0:articel::f("article")
:B0:asdvertising::f("advertising")
:B0:askt he::f("ask the")
:B0:assistent::f("assistant")
:B0:asthe::f("as the")
:B0:atention::f("attention")
:B0:atmospher::f("atmosphere")
:B0:attentioin::f("attention")
:B0:atthe::f("at the")
:B0:audeince::f("audience")
:B0:audiance::f("audience")
:B0:availalbe::f("available")
:B0:awya::f("away")
:B0:aywa::f("away")
:B0:bakc::f("back")
:B0:balence::f("balance")
:B0:ballance::f("balance")
:B0:baout::f("about")
:B0:bcak::f("back")
:B0:beacuse::f("because")
:B0:becasue::f("because")
:B0:becaus::f("because")
:B0:becausea::f("because a")
:B0:becauseof::f("because of")
:B0:becausethe::f("because the")
:B0:becauseyou::f("because you")
:B0:becomeing::f("becoming")
:B0:becomming::f("becoming")
:B0:becuase::f("because")
:B0:becuse::f("because")
:B0:befoer::f("before")
:B0:beggining::f("beginning")
:B0:begining::f("beginning")
:B0:beginining::f("beginning")
:B0:beleiev::f("believe")
:B0:beleieve::f("believe")
:B0:beleif::f("belief")
:B0:beleive::f("believe")
:B0:beleived::f("believed")
:B0:beleives::f("believes")
:B0:benifit::f("benefit")
:B0:benifits::f("benefits")
:B0:betwen::f("between")
:B0:beutiful::f("beautiful")
:B0:blase::f("blasé")
:B0:boxs::f("boxes")
:B0:brodcast::f("broadcast")
:B0:butthe::f("but the")
:B0:bve::f("be")
:B0:byt he::f("by the")
:B0:cafe::f("café")
:B0:caharcter::f("character")
:B0:calcullated::f("calculated")
:B0:calulated::f("calculated")
:B0:can't of been::f("can’t have been")
:B0:can;t::f("can’t")
:B0:candidtae::f("candidate")
:B0:candidtaes::f("candidates")
:B0:catagory::f("category")
:B0:categiory::f("category")
:B0:certian::f("certain")
:B0:challange::f("challenge")
:B0:challanges::f("challenges")
:B0:chaneg::f("change")
:B0:chanegs::f("changes")
:B0:changable::f("changeable")
:B0:changeing::f("changing")
:B0:changng::f("changing")
:B0:charachter::f("character")
:B0:charachters::f("characters")
:B0:charactor::f("character")
:B0:charecter::f("character")
:B0:charector::f("character")
:B0:cheif::f("chief")
:B0:chekc::f("check")
:B0:chnage::f("change")
:B0:cieling::f("ceiling")
:B0:circut::f("circuit")
:B0:claer::f("clear")
:B0:claered::f("cleared")
:B0:claerly::f("clearly")
:B0:cliant::f("client")
:B0:cliche::f("cliché")
:B0:cna::f("can")
:B0:colection::f("collection")
:B0:comanies::f("companies")
:B0:comany::f("company")
:B0:comapnies::f("companies")
:B0:comapny::f("company")
:B0:combintation::f("combination")
:B0:comited::f("committed")
:B0:comittee::f("committee")
:B0:commadn::f("command")
:B0:comming::f("coming")
:B0:commitee::f("committee")
:B0:committe::f("committee")
:B0:committment::f("commitment")
:B0:committments::f("commitments")
:B0:committy::f("committee")
:B0:comntain::f("contain")
:B0:comntains::f("contains")
:B0:compair::f("compare")
:B0:company;s::f("company’s")
:B0:compleated::f("completed")
:B0:compleatly::f("completely")
:B0:compleatness::f("completeness")
:B0:completly::f("completely")
:B0:completness::f("completeness")
:B0:composate::f("composite")
:B0:comtain::f("contain")
:B0:comtains::f("contains")
:B0:comunicate::f("communicate")
:B0:comunity::f("community")
:B0:condolances::f("condolences")
:B0:conected::f("connected")
:B0:conferance::f("conference")
:B0:confirmmation::f("confirmation")
:B0:considerit::f("considerate")
:B0:considerite::f("considerate")
:B0:consonent::f("consonant")
:B0:conspiricy::f("conspiracy")
:B0:consultent::f("consultant")
:B0:convertable::f("convertible")
:B0:cooparate::f("cooperate")
:B0:cooporate::f("cooperate")
:B0:corproation::f("corporation")
:B0:corproations::f("corporations")
:B0:corruptable::f("corruptible")
:B0:cotten::f("cotton")
:B0:coudl::f("could")
:B0:coudln't::f("couldn’t")
:B0:coudn't::f("couldn’t")
:B0:could of been::f("could have been")
:B0:could of had::f("could have had")
:B0:couldn;t::f("couldn’t")
:B0:couldnt::f("couldn’t")
:B0:couldthe::f("could the")
:B0:cpoy::f("copy")
:B0:creme::f("crème")
:B0:ctaegory::f("category")
:B0:cusotmer::f("customer")
:B0:cusotmers::f("customers")
:B0:cutsomer::f("customer")
:B0:cutsomers::f("customers")
:B0:cxan::f("can")
:B0:danceing::f("dancing")
:B0:dcument::f("document")
:B0:deatils::f("details")
:B0:decison::f("decision")
:B0:decisons::f("decisions")
:B0:decor::f("décor")
:B0:defendent::f("defendant")
:B0:definately::f("definitely")
:B0:deja vu::f("déjà vu")
:B0:deptartment::f("department")
:B0:desicion::f("decision")
:B0:desicions::f("decisions")
:B0:desision::f("decision")
:B0:desisions::f("decisions")
:B0:detente::f("détente")
:B0:develeoprs::f("developers")
:B0:devellop::f("develop")
:B0:develloped::f("developed")
:B0:develloper::f("developer")
:B0:devellopers::f("developers")
:B0:develloping::f("developing")
:B0:devellopment::f("development")
:B0:devellopments::f("developments")
:B0:devellops::f("develop")
:B0:develope::f("develop")
:B0:developement::f("development")
:B0:developements::f("developments")
:B0:developor::f("developer")
:B0:developors::f("developers")
:B0:develpment::f("development")
:B0:diaplay::f("display")
:B0:didint::f("didn’t")
:B0:didn;t::f("didn’t")
:B0:didnot::f("did not")
:B0:didnt::f("didn’t")
:B0:difefrent::f("different")
:B0:diferences::f("differences")
:B0:differance::f("difference")
:B0:differances::f("differences")
:B0:differant::f("different")
:B0:differemt::f("different")
:B0:differnt::f("different")
:B0:diffrent::f("different")
:B0:directer::f("director")
:B0:directers::f("directors")
:B0:directiosn::f("direction")
:B0:disatisfied::f("dissatisfied")
:B0:discoverd::f("discovered")
:B0:disign::f("design")
:B0:dispaly::f("display")
:B0:dissonent::f("dissonant")
:B0:distribusion::f("distribution")
:B0:divsion::f("division")
:B0:do'nt::f("don’t")
:B0:docuement::f("documents")
:B0:docuemnt::f("document")
:B0:documetn::f("document")
:B0:documnet::f("document")
:B0:documnets::f("documents")
:B0:doe snot::f("does not")
:B0:doens't::f("doesn’t")
:B0:doese::f("does")
:B0:doesn;t::f("doesn’t")
:B0:doesnt::f("doesn’t")
:B0:doign::f("doing")
:B0:doimg::f("doing")
:B0:doind::f("doing")
:B0:dollers::f("dollars")
:B0:don't no::f("don’t know")
:B0:don;t::f("don’t")
:B0:donig::f("doing")
:B0:dont::f("don’t")
:B0:dosn't::f("doesn’t")
:B0:driveing::f("driving")
:B0:drnik::f("drink")
:B0:eclair::f("éclair")
:B0:efel::f("feel")
:B0:effecient::f("efficient")
:B0:efort::f("effort")
:B0:eforts::f("efforts")
:B0:ehr::f("her")
:B0:eligable::f("eligible")
:B0:embarass::f("embarrass")
:B0:emigre::f("émigré")
:B0:enought::f("enough")
:B0:entree::f("entrée")
:B0:equippment::f("equipment")
:B0:equivalant::f("equivalent")
:B0:esle::f("else")
:B0:especally::f("especially")
:B0:especialyl::f("especially")
:B0:espesially::f("especially")
:B0:excellant::f("excellent")
:B0:excercise::f("exercise")
:B0:exchagne::f("exchange")
:B0:exchagnes::f("exchanges")
:B0:excitment::f("excitement")
:B0:exhcange::f("exchange")
:B0:exhcanges::f("exchanges")
:B0:experiance::f("experience")
:B0:experienc::f("experience")
:B0:exprience::f("experience")
:B0:exprienced::f("experienced")
:B0:eyt::f("yet")
:B0:facade::f("façade")
:B0:faeture::f("feature")
:B0:faetures::f("features")
:B0:familair::f("familiar")
:B0:familar::f("familiar")
:B0:familliar::f("familiar")
:B0:fammiliar::f("familiar")
:B0:feild::f("field")
:B0:feilds::f("fields")
:B0:fianlly::f("finally")
:B0:fidn::f("find")
:B0:finalyl::f("finally")
:B0:firends::f("friends")
:B0:firts::f("first")
:B0:follwo::f("follow")
:B0:follwoing::f("following")
:B0:fora::f("for a")
:B0:foriegn::f("foreign")
:B0:forthe::f("for the")
:B0:forwrd::f("forward")
:B0:forwrds::f("forwards")
:B0:foudn::f("found")
:B0:foward::f("forward")
:B0:fowards::f("forwards")
:B0:freind::f("friend")
:B0:freindly::f("friendly")
:B0:freinds::f("friends")
:B0:frmo::f("from")
:B0:fromt he::f("from the")
:B0:fromthe::f("from the")
:B0:furneral::f("funeral")
:B0:fwe::f("few")
:B0:garantee::f("guarantee")
:B0:gaurd::f("guard")
:B0:gemeral::f("general")
:B0:gerat::f("great")
:B0:geting::f("getting")
:B0:gettin::f("getting")
:B0:gievn::f("given")
:B0:giveing::f("giving")
:B0:gloabl::f("global")
:B0:goign::f("going")
:B0:gonig::f("going")
:B0:govenment::f("government")
:B0:goverment::f("government")
:B0:gruop::f("group")
:B0:gruops::f("groups")
:B0:grwo::f("grow")
:B0:guidlines::f("guidelines")
:B0:hadbeen::f("had been")
:B0:hadn;t::f("hadn’t")
:B0:haev::f("have")
:B0:hapen::f("happen")
:B0:hapened::f("happened")
:B0:hapening::f("happening")
:B0:hapens::f("happens")
:B0:happend::f("happened")
:B0:hasbeen::f("has been")
:B0:hasn;t::f("hasn’t")
:B0:hasnt::f("hasn’t")
:B0:havebeen::f("have been")
:B0:haveing::f("having")
:B0:haven;t::f("haven’t")
:B0:hda::f("had")
:B0:he;ll::f("he’ll")
:B0:hearign::f("hearing")
:B0:helpfull::f("helpful")
:B0:here;s::f("here’s")
:B0:hesaid::f("he said")
:B0:hewas::f("he was")
:B0:hge::f("he")
:B0:hismelf::f("himself")
:B0:hlep::f("help")
:B0:hsa::f("has")
:B0:hsi::f("his")
:B0:hte::f("the")
:B0:htere::f("there")
:B0:htese::f("these")
:B0:htey::f("they")
:B0:hting::f("thing")
:B0:htink::f("think")
:B0:htis::f("this")
:B0:htp::f(":http:")
:B0:http:\\::f("http://")
:B0:httpL::f("http:")
:B0:hvae::f("have")
:B0:hvaing::f("having")
:B0:hwich::f("which")
:B0:i::f("I")
:B0:i snot::f("is not")
:B0:I"m::f("I’m")
:B0:I;d::f("I’d")
:B0:I;ll::f("I’ll")
:B0:idae::f("idea")
:B0:idaes::f("ideas")
:B0:identofy::f("identify")
:B0:ihs::f("his")
:B0:iits the::f("it’s the")
:B0:imediate::f("immediate")
:B0:imediatly::f("immediately")
:B0:immediatly::f("immediately")
:B0:importent::f("important")
:B0:importnat::f("important")
:B0:impossable::f("impossible")
:B0:improvemnt::f("improvement")
:B0:improvment::f("improvement")
:B0:includ::f("include")
:B0:indecate::f("indicate")
:B0:indenpendence::f("independence")
:B0:indenpendent::f("independent")
:B0:indepedent::f("independent")
:B0:independance::f("independence")
:B0:independant::f("independent")
:B0:influance::f("influence")
:B0:infomation::f("information")
:B0:informatoin::f("information")
:B0:inital::f("initial")
:B0:instaleld::f("installed")
:B0:insted::f("instead")
:B0:insurence::f("insurance")
:B0:int he::f("in the")
:B0:inteh::f("in the")
:B0:interum::f("interim")
:B0:inthe::f("in the")
:B0:inwhich::f("in which")
:B0:isn;t::f("isn’t")
:B0:isthe::f("is the")
:B0:it snot::f("it’s not")
:B0:it' snot::f("it’s not")
:B0:it;ll::f("it’ll")
:B0:it;s::f("it’s")
:B0:itis::f("it is")
:B0:ititial::f("initial")
:B0:itnerest::f("interest")
:B0:itnerested::f("interested")
:B0:itneresting::f("interesting")
:B0:itnerests::f("interests")
:B0:its a::f("it’s a")
:B0:its the::f("it’s the")
:B0:itwas::f("it was")
:B0:iwll::f("will")
:B0:iwth::f("with")
:B0:jsut::f("just")
:B0:jugment::f("judgment")
:B0:knowldge::f("knowledge")
:B0:knowlege::f("knowledge")
:B0:knwo::f("know")
:B0:knwon::f("known")
:B0:knwos::f("knows")
:B0:konw::f("know")
:B0:konwn::f("known")
:B0:konws::f("knows")
:B0:labratory::f("laboratory")
:B0:lastyear::f("last year")
:B0:learnign::f("learning")
:B0:lenght::f("length")
:B0:let's him::f("lets him")
:B0:let's it::f("lets it")
:B0:let;s::f("let’s")
:B0:levle::f("level")
:B0:libary::f("library")
:B0:librarry::f("library")
:B0:librery::f("library")
:B0:liek::f("like")
:B0:liekd::f("liked")
:B0:lieutenent::f("lieutenant")
:B0:liev::f("live")
:B0:likly::f("likely")
:B0:lisense::f("license")
:B0:littel::f("little")
:B0:litttle::f("little")
:B0:liuke::f("like")
:B0:liveing::f("living")
:B0:loev::f("love")
:B0:lonly::f("lonely")
:B0:lookign::f("looking")
:B0:maintenence::f("maintenance")
:B0:makeing::f("making")
:B0:managment::f("management")
:B0:mantain::f("maintain")
:B0:marraige::f("marriage")
:B0:may of been::f("may have been")
:B0:may of had::f("may have had")
:B0:memeber::f("member")
:B0:merchent::f("merchant")
:B0:mesage::f("message")
:B0:mesages::f("messages")
:B0:might of been::f("might have been")
:B0:might of had::f("might have had")
:B0:mispell::f("misspell")
:B0:mispelling::f("misspelling")
:B0:mispellings::f("misspellings")
:B0:mkae::f("make")
:B0:mkaes::f("makes")
:B0:mkaing::f("making")
:B0:moeny::f("money")
:B0:morgage::f("mortgage")
:B0:mroe::f("more")
:B0:must of been::f("must have been")
:B0:must of had::f("must have had")
:B0:mysefl::f("myself")
:B0:myu::f("my")
:B0:naive::f("naïve")
:B0:necassarily::f("necessarily")
:B0:necassary::f("necessary")
:B0:neccessarily::f("necessarily")
:B0:neccessary::f("necessary")
:B0:necesarily::f("necessarily")
:B0:necesary::f("necessary")
:B0:negotiaing::f("negotiating")
:B0:nkow::f("know")
:B0:nothign::f("nothing")
:B0:nver::f("never")
:B0:nwe::f("new")
:B0:nwo::f("now")
:B0:obediant::f("obedient")
:B0:ocasion::f("occasion")
:B0:occassion::f("occasion")
:B0:occured::f("occurred")
:B0:occurence::f("occurrence")
:B0:occurrance::f("occurrence")
:B0:ocur::f("occur")
:B0:oeprator::f("operator")
:B0:ofits::f("of its")
:B0:oft he::f("of the")
:B0:ofthe::f("of the")
:B0:oging::f("going")
:B0:ohter::f("other")
:B0:omre::f("more")
:B0:oneof::f("one of")
:B0:onepoint::f("one point")
:B0:ont he::f("on the")
:B0:onthe::f("on the")
:B0:onyl::f("only")
:B0:oppasite::f("opposite")
:B0:opperation::f("operation")
:B0:oppertunity::f("opportunity")
:B0:opposate::f("opposite")
:B0:opposible::f("opposable")
:B0:opposit::f("opposite")
:B0:oppotunities::f("opportunities")
:B0:oppotunity::f("opportunity")
:B0:orginization::f("organization")
:B0:orginized::f("organized")
:B0:otehr::f("other")
:B0:otu::f("out")
:B0:outof::f("out of")
:B0:overthe::f("over the")
:B0:owrk::f("work")
:B0:owuld::f("would")
:B0:oxident::f("oxidant")
:B0:papaer::f("paper")
:B0:parliment::f("parliament")
:B0:partof::f("part of")
:B0:paymetn::f("payment")
:B0:paymetns::f("payments")
:B0:pciture::f("picture")
:B0:peice::f("piece")
:B0:peices::f("pieces")
:B0:peolpe::f("people")
:B0:peopel::f("people")
:B0:percentof::f("percent of")
:B0:percentto::f("percent to")
:B0:performence::f("performance")
:B0:perhasp::f("perhaps")
:B0:perhpas::f("perhaps")
:B0:permanant::f("permanent")
:B0:perminent::f("permanent")
:B0:personalyl::f("personally")
:B0:pleasent::f("pleasant")
:B0:poeple::f("people")
:B0:porblem::f("problem")
:B0:porblems::f("problems")
:B0:porvide::f("provide")
:B0:possable::f("possible")
:B0:postition::f("position")
:B0:potentialy::f("potentially")
:B0:pregnent::f("pregnant")
:B0:presance::f("presence")
:B0:probelm::f("problem")
:B0:probelms::f("problems")
:B0:prominant::f("prominent")
:B0:protege::f("protégé")
:B0:protoge::f("protégé")
:B0:psoition::f("position")
:B0:ptogress::f("progress")
:B0:puting::f("putting")
:B0:pwoer::f("power")
:B0:quater::f("quarter")
:B0:quaters::f("quarters")
:B0:quesion::f("question")
:B0:quesions::f("questions")
:B0:questioms::f("questions")
:B0:questiosn::f("questions")
:B0:questoin::f("question")
:B0:quetion::f("question")
:B0:quetions::f("questions")
:B0:realyl::f("really")
:B0:reccomend::f("recommend")
:B0:reccommend::f("recommend")
:B0:receieve::f("receive")
:B0:recieve::f("receive")
:B0:recieved::f("received")
:B0:recieving::f("receiving")
:B0:recomend::f("recommend")
:B0:recomendation::f("recommendation")
:B0:recomendations::f("recommendations")
:B0:recomended::f("recommended")
:B0:reconize::f("recognize")
:B0:recrod::f("record")
:B0:religous::f("religious")
:B0:reluctent::f("reluctant")
:B0:remeber::f("remember")
:B0:reommend::f("recommend")
:B0:representativs::f("representatives")
:B0:representives::f("representatives")
:B0:represetned::f("represented")
:B0:represnt::f("represent")
:B0:reserach::f("research")
:B0:resollution::f("resolution")
:B0:resorces::f("resources")
:B0:respomd::f("respond")
:B0:respomse::f("response")
:B0:responce::f("response")
:B0:responsability::f("responsibility")
:B0:responsable::f("responsible")
:B0:responsibile::f("responsible")
:B0:responsiblity::f("responsibility")
:B0:restaraunt::f("restaurant")
:B0:restuarant::f("restaurant")
:B0:reult::f("result")
:B0:reveiw::f("review")
:B0:reveiwing::f("reviewing")
:B0:rwite::f("write")
:B0:rythm::f("rhythm")
:B0:saidhe::f("said he")
:B0:saidit::f("said it")
:B0:saidt he::f("said the")
:B0:saidthat::f("said that")
:B0:saidthe::f("said the")
:B0:scedule::f("schedule")
:B0:sceduled::f("scheduled")
:B0:seance::f("séance")
:B0:secratary::f("secretary")
:B0:sectino::f("section")
:B0:seh::f("she")
:B0:selectoin::f("selection")
:B0:sentance::f("sentence")
:B0:separeate::f("separate")
:B0:seperate::f("separate")
:B0:sercumstances::f("circumstances")
:B0:shcool::f("school")
:B0:she;ll::f("she’ll")
:B0:shesaid::f("she said")
:B0:shineing::f("shining")
:B0:shiped::f("shipped")
:B0:shoudl::f("should")
:B0:shoudln't::f("shouldn’t")
:B0:should of been::f("should have been")
:B0:should of had::f("should have had")
:B0:shouldent::f("shouldn’t")
:B0:shouldn;t::f("shouldn’t")
:B0:shouldnt::f("shouldn’t")
:B0:showinf::f("showing")
:B0:signifacnt::f("significant")
:B0:simalar::f("similar")
:B0:similiar::f("similar")
:B0:simpyl::f("simply")
:B0:sincerly::f("sincerely")
:B0:sitll::f("still")
:B0:smae::f("same")
:B0:smoe::f("some")
:B0:soem::f("some")
:B0:sohw::f("show")
:B0:soical::f("social")
:B0:somethign::f("something")
:B0:someting::f("something")
:B0:somewaht::f("somewhat")
:B0:somthing::f("something")
:B0:somtimes::f("sometimes")
:B0:sot hat::f("so that")
:B0:soudn::f("sound")
:B0:soudns::f("sounds")
:B0:speach::f("speech")
:B0:specificaly::f("specifically")
:B0:specificalyl::f("specifically")
:B0:statment::f("statement")
:B0:statments::f("statements")
:B0:stnad::f("stand")
:B0:stopry::f("story")
:B0:stoyr::f("story")
:B0:stpo::f("stop")
:B0:strentgh::f("strength")
:B0:stroy::f("story")
:B0:struggel::f("struggle")
:B0:strugle::f("struggle")
:B0:studnet::f("student")
:B0:successfull::f("successful")
:B0:successfuly::f("successfully")
:B0:successfulyl::f("successfully")
:B0:sucess::f("success")
:B0:sucessfull::f("successful")
:B0:sufficiant::f("sufficient")
:B0:suposed::f("supposed")
:B0:suppossed::f("supposed")
:B0:suprise::f("surprise")
:B0:suprised::f("surprised")
:B0:swiming::f("swimming")
:B0:tahn::f("than")
:B0:taht::f("that")
:B0:talekd::f("talked")
:B0:talkign::f("talking")
:B0:tath::f("that")
:B0:tecnical::f("technical")
:B0:teh::f("the")
:B0:tehy::f("they")
:B0:tellt he::f("tell the")
:B0:termoil::f("turmoil")
:B0:tghe::f("the")
:B0:tghis::f("this")
:B0:thansk::f("thanks")
:B0:thats::f("that’s")
:B0:thatt he::f("that the")
:B0:thatthe::f("that the")
:B0:thecompany::f("the company")
:B0:thefirst::f("the first")
:B0:thegovernment::f("the government")
:B0:their are::f("there are")
:B0:their is::f("there is")
:B0:themself::f("themselves")
:B0:themselfs::f("themselves")
:B0:thenew::f("the new")
:B0:there's is::f("theirs is")
:B0:theri::f("their")
:B0:thesame::f("the same")
:B0:thetwo::f("the two")
:B0:they're are::f("there are")
:B0:they're is::f("there is")
:B0:they;l::f("they’ll")
:B0:they;ll::f("they’ll")
:B0:they;r::f("they’re")
:B0:they;re::f("they’re")
:B0:they;v::f("they’ve")
:B0:they;ve::f("they’ve")
:B0:theyll::f("they’ll")
:B0:theyve::f("they’ve")
:B0:thgat::f("that")
:B0:thge::f("the")
:B0:thier::f("their")
:B0:thigsn::f("things")
:B0:thisyear::f("this year")
:B0:thna::f("than")
:B0:thne::f("then")
:B0:thnig::f("thing")
:B0:thnigs::f("things")
:B0:threatend::f("threatened")
:B0:thsi::f("this")
:B0:thsoe::f("those")
:B0:thta::f("that")
:B0:tihs::f("this")
:B0:timne::f("time")
:B0:tiogether::f("together")
:B0:tje::f("the")
:B0:tjhe::f("the")
:B0:tkae::f("take")
:B0:tkaes::f("takes")
:B0:tkaing::f("taking")
:B0:tlaking::f("talking")
:B0:todya::f("today")
:B0:togehter::f("together")
:B0:toldt he::f("told the")
:B0:tomorow::f("tomorrow")
:B0:tongiht::f("tonight")
:B0:tonihgt::f("tonight")
:B0:tot he::f("to the")
:B0:totaly::f("totally")
:B0:totalyl::f("totally")
:B0:tothe::f("to the")
:B0:towrad::f("toward")
:B0:traditionalyl::f("traditionally")
:B0:transfered::f("transferred")
:B0:truely::f("truly")
:B0:truley::f("truly")
:B0:tryed::f("tried")
:B0:tthe::f("the")
:B0:tyhat::f("that")
:B0:tyhe::f("the")
:B0:udnerstand::f("understand")
:B0:understnad::f("understand")
:B0:undert he::f("under the")
:B0:UnitedStates::f("United States")
:B0:unliek::f("unlike")
:B0:unpleasently::f("unpleasantly")
:B0:untilll::f("until")
:B0:useing::f("using")
:B0:usualyl::f("usually")
:B0:veyr::f("very")
:B0:virtualyl::f("virtually")
:B0:vis-a-vis::f("vis-à-vis")
:B0:vrey::f("very")
:B0:vulnerible::f("vulnerable")
:B0:wa snot::f("was not")
:B0:waht::f("what")
:B0:warrent::f("warrant")
:B0:wasnt::f("wasn’t")
:B0:watn::f("want")
:B0:we;d::f("we’d")
:B0:we;ll::f("we’ll")
:B0:we;re::f("we’re")
:B0:we;ve::f("we’ve")
:B0:wehn::f("when")
:B0:wern't::f("weren’t")
:B0:werre::f("were")
:B0:what;s::f("what’s")
:B0:whcih::f("which")
:B0:whent he::f("when the")
:B0:where;s::f("where’s")
:B0:wherre::f("where")
:B0:whic::f("which")
:B0:whicht he::f("which the")
:B0:whihc::f("which")
:B0:who;s::f("who’s")
:B0:who;ve::f("who’ve")
:B0:whta::f("what")
:B0:wief::f("wife")
:B0:wierd::f("weird")
:B0:wihch::f("which")
:B0:wiht::f("with")
:B0:will of been::f("will have been")
:B0:will of had::f("will have had")
:B0:willbe::f("will be")
:B0:windoes::f("windows")
:B0:witha::f("with a")
:B0:withe::f("with")
:B0:witht he::f("with the")
:B0:withthe::f("with the")
:B0:wiull::f("will")
:B0:wnat::f("want")
:B0:wnated::f("wanted")
:B0:wnats::f("wants")
:B0:wo'nt::f("won’t")
:B0:woh::f("who")
:B0:wohle::f("whole")
:B0:wokr::f("work")
:B0:won;t::f("won’t")
:B0:woudl::f("would")
:B0:woudln't::f("wouldn’t")
:B0:would of been::f("would have been")
:B0:would of had::f("would have had")
:B0:wouldbe::f("would be")
:B0:wouldn;t::f("wouldn’t")
:B0:wouldnt::f("wouldn’t")
:B0:wriet::f("write")
:B0:writting::f("writing")
:B0:wrod::f("word")
:B0:wroet::f("wrote")
:B0:wroking::f("working")
:B0:wtih::f("with")
:B0:wuould::f("would")
:B0:wya::f("way")
:B0:yera::f("year")
:B0:yeras::f("years")
:B0:yersa::f("years")
:B0:yoiu::f("you")
:B0:you're own::f("your own")
:B0:you;d::f("you’d")
:B0:you;re::f("you’re")
:B0:youare::f("you are")
:B0:your a::f("you’re a")
:B0:your an::f("you’re an")
:B0:your her::f("you’re her")
:B0:your here::f("you’re here")
:B0:your his::f("you’re his")
:B0:your the::f("you’re the")
:B0:your their::f("you’re their")
:B0:your your::f("you’re your")
:B0:youve::f("you’ve")
:B0:ytou::f("you")
:B0:yuo::f("you")
:B0:yuor::f("your")
