# Zsh-compatible aliases (POSIX alias syntax).
# AUTO-GENERATED from aliases.toml — do not edit directly.

alias grep='grep --color=always'
alias diff='diff --color=always'
alias rg='rg --color=always --hyperlink-format=default'
alias fd='fd --color=always --hyperlink'
alias jq='jq -C'
alias ip='ip -c'
alias bat='bat --color=always --hyperlink=auto'
alias eza='eza --icons=always --group-directories-first --git --color=always --hyperlink'

alias reload='exec $SHELL -l'
alias cls='clear'
alias v='$EDITOR'
alias mkd='mkdir -pv'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git pull'
alias gd='git diff'
alias gl='git log --oneline --decorate --graph -20'
alias gst='git status -sb'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcm='git commit -m'

alias lg='lazygit'
alias calc='qalc'
alias d='delta'
alias gpu='nvtop'
alias tv='television'
alias mcpp='mcp-probe'
alias bw='bandwhich'
alias samp='sampler'
alias todo='task'
alias snippets='pet'
alias getgh='eget'
alias kb='tldr'
alias tl='tldr'
alias jl='jless'
alias md='glow'
alias hx='helix'
alias fm='yazi'
alias xp='xplr'
alias br='broot'
alias bench='hyperfine'
alias http='xh'
alias hex='hexyl'

alias top='btop'
alias df='duf'
alias du='dust'
alias ps='procs'
alias dig='doggo'
alias x='ouch decompress'

alias t='tmux -2'
alias ta='tmux attach -t'
alias tls='tmux ls'
alias tn='tmux new -s'

alias jqp='jq -C .'
alias fda='fd -HI --color=always --hyperlink'
alias ccat='bat --color=always --hyperlink=auto --paging=never --style=header,grid,numbers,changes'
alias ports='ss -tulpn'
alias ipbrief='ip -c -br a'
alias ff='plocate'
alias rgf='rg -n --color=always --hyperlink-format=default'
alias cronview='cronboard'
alias j='z'
