;------------------------------------------------------------------------------
; Accented English words, from, amongst others,
; http://en.wikipedia.org/wiki/List_of_English_words_with_diacritics
; I have included all the ones compatible with reasonable codepages, and placed
; those that may often not be accented either from a clash with an unaccented 
; word (resume), or because the unaccented version is now common (cafe).
;------------------------------------------------------------------------------
:B0:aesop::f("Æsop")
:B0:a bas::f("à bas")
:B0:a la::f("à la")
:B0:ancien regime::f("Ancien Régime")
:B0:angstrom::f("Ångström")
:B0:angstroms::f("Ångströms")
:B0:anime::f("animé")
:B0:animes::f("animés")
:B0:ao dai::f("ào dái")
:B0:apertif::f("apértif")
:B0:apertifs::f("apértifs")
:B0:applique::f("appliqué")
:B0:appliques::f("appliqués")
:B0:apres::f("après")
:B0:arete::f("arête")
:B0:attache::f("attaché")
:B0:attaches::f("attachés")
:B0:auto-da-fe::f("auto-da-fé")
:B0:belle epoque::f("belle époque")
:B0:bete noire::f("bête noire")
:B0:betise::f("bêtise")
:B0:Bjorn::f("Bjørn")
:B0:blase::f("blasé")
:B0:boite::f("boîte")
:B0:boutonniere::f("boutonnière")
:B0:canape::f("canapé")
:B0:canapes::f("canapés")
:B0:celebre::f("célèbre")
:B0:celebres::f("célèbres")
:B0:chaines::f("chaînés")
:B0:cinema verite::f("cinéma vérité")
:B0:cinemas verite::f("cinémas vérité")
:B0:cinema verites::f("cinéma vérités")
:B0:champs-elysees::f("Champs-Élysées")
:B0:charge d'affaires::f("chargé d'affaires")
:B0:chateau::f("château")
:B0:chateaux::f("châteaux")
:B0:chateaus::f("châteaus")
:B0:cliche::f("cliché")
:B0:cliched::f("clichéd")
:B0:cliches::f("clichés")
:B0:cloisonne::f("cloisonné")
:B0:consomme::f("consommé")
:B0:consommes::f("consommés")
:B0:communique::f("communiqué")
:B0:communiques::f("communiqués")
:B0:confrere::f("confrère")
:B0:confreres::f("confrères")
:B0:cortege::f("cortège")
:B0:corteges::f("cortèges")
:B0:coup d'etat::f("coup d'état")
:B0:coup d'etats::f("coup d'états")
:B0:coup de tat::f("coup d'état")
:B0:coup de tats::f("coup d'états")
:B0:coup de grace::f("coup de grâce")
:B0:creche::f("crèche")
:B0:creches::f("crèches")
:B0:coulee::f("coulée")
:B0:coulees::f("coulées")
:B0:creme brulee::f("crème brûlée")
:B0:creme brulees::f("crème brûlées")
:B0:creme caramel::f("crème caramel")
:B0:creme caramels::f("crème caramels")
:B0:creme de cacao::f("crème de cacao")
:B0:creme de menthe::f("crème de menthe")
:B0:crepe::f("crêpe")
:B0:crepes::f("crêpes")
:B0:creusa::f("Creüsa")
:B0:crouton::f("croûton")
:B0:croutons::f("croûtons")
:B0:crudites::f("crudités")
:B0:curacao::f("curaçao")
:B0:dais::f("daïs")
:B0:daises::f("daïses")
:B0:debacle::f("débâcle")
:B0:debacles::f("débâcles")
:B0:debutante::f("débutante")
:B0:debutants::f("débutants")
:B0:declasse::f("déclassé")
:B0:decolletage::f("décolletage")
:B0:decollete::f("décolleté")
:B0:decor::f("décor")
:B0:decors::f("décors")
:B0:decoupage::f("découpage")
:B0:degage::f("dégagé")
:B0:deja vu::f("déjà vu")
:B0:demode::f("démodé")
:B0:denoument::f("dénoument")
:B0:derailleur::f("dérailleur")
:B0:derriere::f("derrière")
:B0:deshabille::f("déshabillé")
:B0:detente::f("détente")
:B0:diamante::f("diamanté")
:B0:discotheque::f("discothèque")
:B0:discotheques::f("discothèques")
:B0:divorcee::f("divorcée")
:B0:divorcees::f("divorcées")
:B0:doppelganger::f("doppelgänger")
:B0:doppelgangers::f("doppelgängers")
:B0:eclair::f("éclair")
:B0:eclairs::f("éclairs")
:B0:eclat::f("éclat")
:B0:el nino::f("El Niño")
:B0:elan::f("élan")
:B0:emigre::f("émigré")
:B0:emigres::f("émigrés")
:B0:entree::f("entrée")
:B0:entrees::f("entrées")
:B0:entrepot::f("entrepôt")
:B0:entrecote::f("entrecôte")
:B0:epee::f("épée")
:B0:epees::f("épées")
:B0:etouffee::f("étouffée")
:B0:facade::f("façade")
:B0:facades::f("façades")
:B0:fete::f("fête")
:B0:fetes::f("fêtes")
:B0:faience::f("faïence")
:B0:fiance::f("fiancé")
:B0:fiances::f("fiancés")
:B0:fiancee::f("fiancée")
:B0:fiancees::f("fiancées")
:B0:filmjolk::f("filmjölk")
:B0:fin de siecle::f("fin de siècle")
:B0:flambe::f("flambé")
:B0:flambes::f("flambés")
:B0:fleche::f("flèche")
:B0:Fohn wind::f("Föhn wind")
:B0:folie a deux::f("folie à deux")
:B0:folies a deux::f("folies à deux")
:B0:fouette::f("fouetté")
:B0:frappe::f("frappé")
:B0:frappes::f("frappés")
:B0?*:fraulein::f("fräulein")
:B0?*:fuhrer::f("Führer")
:B0:garcon::f("garçon")
:B0:garcons::f("garçons")
:B0:gateau::f("gâteau")
:B0:gateaus::f("gâteaus")
:B0:gateaux::f("gâteaux")
:B0:gemutlichkeit::f("gemütlichkeit")
:B0:glace::f("glacé")
:B0:glogg::f("glögg")
:B0:gewurztraminer::f("Gewürztraminer")
:B0:gotterdammerung::f("Götterdämmerung")
:B0:grafenberg spot::f("Gräfenberg spot")
:B0:habitue::f("habitué")
:B0:ingenue::f("ingénue")
:B0:jager::f("jäger")
:B0:jalapeno::f("jalapeño")
:B0:jalapenos::f("jalapeños")
:B0:jardiniere::f("jardinière")
:B0:krouzek::f("kroužek")
:B0:kummel::f("kümmel")
:B0:kaldolmar::f("kåldolmar")
:B0:landler::f("ländler")
:B0:langue d'oil::f("langue d'oïl")
:B0:la nina::f("La Niña")
:B0:litterateur::f("littérateur")
:B0:lycee::f("lycée")
:B0:macedoine::f("macédoine")
:B0:macrame::f("macramé")
:B0:maitre d'hotel::f("maître d'hôtel")
:B0:malaguena::f("malagueña")
:B0:manana::f("mañana")
:B0:manege::f("manège")
:B0:manque::f("manqué")
:B0:materiel::f("matériel")
:B0:matinee::f("matinée")
:B0:matinees::f("matinées")
:B0:melange::f("mélange")
:B0:melee::f("mêlée")
:B0:melees::f("mêlées")
:B0:menage a trois::f("ménage à trois")
:B0:menages a trois::f("ménages à trois")
:B0:mesalliance::f("mésalliance")
:B0:metier::f("métier")
:B0:minaudiere::f("minaudière")
:B0:mobius strip::f("Möbius strip")
:B0:mobius strips::f("Möbius strips")
:B0:moire::f("moiré")
:B0:moireing::f("moiréing")
:B0:moires::f("moirés")
:B0:motley crue::f("Mötley Crüe")
:B0:motorhead::f("Motörhead")
:B0:naif::f("naïf")
:B0:naifs::f("naïfs")
:B0:naive::f("naïve")
:B0:naiver::f("naïver")
:B0:naives::f("naïves")
:B0:naivete::f("naïveté")
:B0:nee::f("née")
:B0:negligee::f("negligée")
:B0:negligees::f("negligées")
:B0:neufchatel cheese::f("Neufchâtel cheese")
:B0:nez perce::f("Nez Percé")
:B0:noël::f("Noël")
:B0:noëls::f("Noëls")
:B0:número uno::f("número uno")
:B0:objet trouve::f("objet trouvé")
:B0:objets trouve::f("objets trouvé")
:B0:ombre::f("ombré")
:B0:ombres::f("ombrés")
:B0:omerta::f("omertà")
:B0:opera bouffe::f("opéra bouffe")
:B0:operas bouffe::f("opéras bouffe")
:B0:opera comique::f("opéra comique")
:B0:operas comique::f("opéras comique")
:B0:outre::f("outré")
:B0:papier-mache::f("papier-mâché")
:B0:passe::f("passé")
:B0:piece de resistance::f("pièce de résistance")
:B0:pied-a-terre::f("pied-à-terre")
:B0:plisse::f("plissé")
:B0:pina colada::f("Piña Colada")
:B0:pina coladas::f("Piña Coladas")
:B0:pinata::f("piñata")
:B0:pinatas::f("piñatas")
:B0:pinon::f("piñon")
:B0:pinons::f("piñons")
:B0:pirana::f("piraña")
:B0:pique::f("piqué")
:B0:piqued::f("piquéd")
:B0:più::f("più")
:B0:plie::f("plié")
:B0:precis::f("précis")
:B0:polsa::f("pölsa")
:B0:pret-a-porter::f("prêt-à-porter")
:B0:protoge::f("protégé")
:B0:protege::f("protégé")
:B0:proteged::f("protégéd")
:B0:proteges::f("protégés")
:B0:protegee::f("protégée")
:B0:protegees::f("protégées")
:B0:protegeed::f("protégéed")
:B0:puree::f("purée")
:B0:pureed::f("puréed")
:B0:purees::f("purées")
:B0:Quebecois::f("Québécois")
:B0:raison d'etre::f("raison d'être")
:B0:recherche::f("recherché")
:B0:reclame::f("réclame")
:B0:résume::f("résumé")
:B0:resumé::f("résumé")
:B0:résumes::f("résumés")
:B0:resumés::f("résumés")
:B0:retrousse::f("retroussé")
:B0:risque::f("risqué")
:B0:riviere::f("rivière")
:B0:roman a clef::f("roman à clef")
:B0:roue::f("roué")
:B0:saute::f("sauté")
:B0:sauted::f("sautéd")
:B0:seance::f("séance")
:B0:seances::f("séances")
:B0:senor::f("señor")
:B0:senors::f("señors")
:B0:senora::f("señora")
:B0:senoras::f("señoras")
:B0:senorita::f("señorita")
:B0:senoritas::f("señoritas")
:B0:sinn fein::f("Sinn Féin")
:B0:smorgasbord::f("smörgåsbord")
:B0:smorgasbords::f("smörgåsbords")
:B0:smorgastarta::f("smörgåstårta")
:B0:soigne::f("soigné")
:B0:soiree::f("soirée")
:B0:soireed::f("soiréed")
:B0:soirees::f("soirées")
:B0:souffle::f("soufflé")
:B0:souffles::f("soufflés")
:B0:soupcon::f("soupçon")
:B0:soupcons::f("soupçons")
:B0:surstromming::f("surströmming")
:B0:tete-a-tete::f("tête-à-tête")
:B0:tete-a-tetes::f("tête-à-têtes")
:B0:touche::f("touché")
:B0:tourtiere::f("tourtière")
:B0:ubermensch::f("Übermensch")
:B0:ubermensches::f("Übermensches")
:B0:ventre a terre::f("ventre à terre")
:B0:vicuna::f("vicuña")
:B0:vin rose::f("vin rosé")
:B0:vins rose::f("vins rosé")
:B0:vis a vis::f("vis à vis")
:B0:vis-a-vis::f("vis-à-vis")
:B0:voila::f("voilà ")
